name: Draft Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      # Get the current Zulu date in YYYY.MM.DD.HHMMZ format
      - name: Get Zulu time
        id: zulu_time
        run: |
          ZULU_DATE=$(date -u +"%Y.%m.%d.%H%MZ")
          echo "zulu_time=$ZULU_DATE" >> $GITHUB_ENV

      # Create the release using a script
      - name: Create Release
        uses: actions/github-script@v7
        with:
          script: |
            const { zulu_time } = process.env;
            const response = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: zulu_time,
              name: zulu_time,
              body: "",  // Set body to an empty string instead of null
              draft: false,  // Publish the release immediately
              prerelease: false,  // Ensure it's not a prerelease
              generate_release_notes: true  // Auto-generate changelog
            });
            core.setOutput('release_id', response.data.id);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          zulu_time: ${{ env.zulu_time }}
